version: '3.4'

services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_test
    volumes:
      - pgData:/var/lib/posrtgresql/data
    ports:
      - "8001:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: local@test.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgAdminData:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    depends_on:
      - db

  

volumes:
  pgData:
  pgAdminData:
  